### ISSUE TITLE
Incorrect bytes pass to getParamSize for ES512

### ISSUE THREAD

**Issue by gdiva** [Brightspace/node-ecdsa-sig-formatter#32]
The function getParamSize should be passed 512 not 521 bytes for algo ES512.

**Comment by omsmith** [comment]
Common mistake, but 521 is correct. Thanks for your interest!

https://datatracker.ietf.org/doc/html/rfc7518#section-3.4

| "alg" Param Value | Digital Signature Algorithm  |
| -- | -- |
| ES512 | ECDSA using P-521 and SHA-512

> For ECDSA P-521 SHA-512, R and S will be 521 bits each
